interface IProduct{
description?:string;
imageUrl:string;

}

export const Products:IProduct[] =[
{
    description:"Head and Shoulders šampon: 2,33 KM",
    imageUrl:"./images/head_and_shoulders.jpeg"
},
{
    description:"",
    imageUrl:"./images/palmolive.jpg"
},
{
    description:"",
    imageUrl:"./images/dove2.jpg"
},
{
    description:"",
    imageUrl:"./images/gileteblue.jpg"
},
{
    description:"",
    imageUrl:"./images/colgate.jpg"
},
{
    description:"",
    imageUrl:"./images/maske.jpg"
},
{
    description:"",
    imageUrl:"./images/bicmali.jpg"
},
{
    description:"",
    imageUrl:"./images/bicsrednji.jpg"
},
{
    description:"",
    imageUrl:"./images/askupaljac.jpg"
},
{
    description:"",
    imageUrl:"./images/mars1.jpg"
},
{
    description:"",
    imageUrl:"./images/snickers10kom.jpg"
},
{
    description:"",
    imageUrl:"./images/marsmini.jpg"
},
{
    description:"",
    imageUrl:"./images/snikersmini.jpg"
},
{
    description:"",
    imageUrl:"./images/bountyminis.jpg"
},
{
    description:"Milky ways mini cijena 3.30KM",
    imageUrl:"./images/milkywaysmini.jpg"
},
{
    description:"",
    imageUrl:"./images/kindercok.jpg"
},
{
    description:"Crni 1.00 KM Bijeli 1.08 KM",
    imageUrl:"./images/kinderbueno.jpg"
},
{
    description:"Bounty 24x57g cijena: 0,75KM",
    imageUrl:"./images/bounty.jpg"
},
{
    description:"",
    imageUrl:"./images/milkanoisette.jpg" 
},
{
    description:"",
    imageUrl:"./images/shoxbar1.jpg"
},
{
    description:"",
    imageUrl:"./images/shoxbarcaramel.jpg"
},
{
    description:"",
    imageUrl:"./images/dalecoko.jpg"
},
{
    description:"",
    imageUrl:"./images/snackcoko.jpg"
},
{
    description:"",
    imageUrl:"./images/cokobarkokos.jpg"
},
{
    description:"",
    imageUrl:"./images/crunchycoko.jpg"
},
{
    description:"",
    imageUrl:"./images/crunchy2.jpg"
},
{
    description:"",
    imageUrl:"./images/biskvittam.jpg"
},
{
    description:"",
    imageUrl:"./images/kremstapici.jpg"
},
{
    description:"",
    imageUrl:"./images/bistela.jpg"
},
{
    description:"",
    imageUrl:"./images/biskvittam.jpg"
},
{
    description:"",
    imageUrl:"./images/cokojaja.jpg"
},

{
    description:"",
    imageUrl:"./images/haribogoldbears.jpg"
},
{
    description:"",
    imageUrl:"./images/lizala150kom.jpg"
},
{
    description:"Haribo 1.00KM",
    imageUrl:"./images/haribo.jpg"
},
{
    description:"",
    imageUrl:"./images/secernavuna.jpg"
},
{
    description:"",
    imageUrl:"./images/dimessok.jpg"
},
{
    description:"Ronin energy drink 0.5l cijena: 0.75KM",
    imageUrl:"./images/ronin.jpg"
}



];